format = """
[$time=> ](fg:#ffffff)\
$directory\
$git_branch\
$git_status\
$nodejs\
\n$character"""

[username]
show_always = true
format = "[$user]($style_user)"
style_user = "fg:#ffffff"
style_root = "fg:#8cff59"

[hostname]
ssh_only = false
disabled = false
format = "[@$hostname](bold blue)"

[directory]
style = "fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Development" = ""

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:#a98dfd)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#2986cc bg:#394260)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#64b940)]($style)'

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb)]($style)'
use_12hr = true

